language: python
dist: trusty
sudo: false
virtualenv:
  system_site_packages: true
python:
  - "3.4"
addons:
  apt:
    packages:
    - python3-gi
    - python3-pep8
    - python3-pexpect
    - python3-pyflakes
    - python3-requests
install: ""
script: PATH="/usr/bin:$PATH" ./runtests
