language: python
dist: trusty
sudo: false
addons:
  apt:
    packages:
    - python3-pytest
    - python3-pep8
python:
  - "3.6"
install:
  - pip install -r requirements.txt
script: PATH="/usr/bin:$PATH" ./runtests pep8 tools
