language: python
dist: trusty
sudo: true
virtualenv:
  system_site_packages: true
python:
  - "3.6"
addons:
  apt:
    packages:
    - python3-pep8
install:
  - pip install -r requirements.txt
script: PATH="/usr/bin:$PATH" ./runtests tests.CodeCheck.test_pycodestyle
