#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import argparse
import os
import sys
import logging
import unittest
import re
import pytest
from glob import glob

logger = logging.getLogger(__name__)
root_dir = os.path.abspath(os.path.dirname(__file__))
TESTS_DIR = os.path.join(root_dir, 'tests')

def run_test(tests):
    tests = []
    if len(args.tests) > 0:
        for test_type in args.tests:
            if test_type in ("pep8", "pyflakes", "tools"):
                if test_type == "pep8":
                    tests.append(os.path.join(TESTS_DIR, "__init__.py"))
                elif test_type == "pyflakes":
                    tests.append(os.path.join(TESTS_DIR, "test_style.py"))
                elif test_type == "tools":
                    tests.append(os.path.join(TESTS_DIR, "test_tools.py"))
            elif test_type in args.tests:
                # Append the file if it exists
                if os.path.exists(test_type):
                    tests.append(test_type)
                else:
                    logger.error("The test you are running does not exist.")
                    return
    else:
        print('No test selected. Run all the tests')
        tests.append(os.path.join(TESTS_DIR, "__init__.py"))
        tests.extend(glob(os.path.join(TESTS_DIR, "test_*.py")))
    pytest.main(args=tests)


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description="Run tests.")
    parser.add_argument("tests", nargs='*', help='Use dot notation \
                                                  starting from the tests folder')
    args = parser.parse_args()
    run_test(args.tests)
