#!/usr/bin/env python3

import argparse
import os
import nose
import logging
import unittest
from tests import CodeCheck

logger = logging.getLogger(__name__)
root_dir = os.path.abspath(os.path.dirname(__file__))
TESTS_DIR = os.path.join(root_dir, 'tests')

def run_test(args):
    tests = []
    loader = unittest.TestLoader()
    if len(args.tests) > 0:
        for test in args.tests:
            if test in ('pass', 'pep8'):
                if test == 'pep8':
                    suite = loader.loadTestsFromTestCase(CodeCheck)
                    tests.append(suite)
            else:
                logger.error('{} is not a valid test, skipping.'.format(test))
    else:
        logger.debug('No test selected. Testing pep8 by default')
        suite = loader.loadTestsFromTestCase(CodeCheck)
        tests.append(suite)

    full_test = unittest.TestSuite(tests)
    runner = unittest.TextTestRunner()
    runner.run(full_test)


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description="Run tests.")
    parser.add_argument("tests", nargs='*', help='Options: pep8')
    args = parser.parse_args()
    run_test(args)
