name: grive-indicator
adopt-info: grive-indicator
license: GPL-3.0
summary: Appindicator menu for Grive2
description: |
  Appindicator support for Grive2, the Google Drive sync tool.
  Easily sync your Google Drive account from a ui indicator.

grade: stable
confinement: strict
base: core18

apps:
  grive-indicator:
    command: bin/grive-indicator
    desktop: usr/share/applications/grive-indicator.desktop
    passthrough:
      autostart: grive-indicator
    extensions: [gnome-3-28]
    plugs:
      - home
      - network
      - gsettings
      - unity7
  grive:
    command: bin/grive
    extensions: [gnome-3-28]
    plugs:
      - home
      - network

slots:
  # for GtkApplication registration
  grive-indicator-dbus:
    interface: dbus
    name: com.github.lyzardking.grive_indicator
    bus: session

parts:
  grive-indicator:
    source: .
    source-type: git
    plugin: python
    python-version: python3
    stage-packages:
      - python3-gi
      - python3-dbus
      - python3-requests
      - python3-toml
      - python3-xdg
      - gir1.2-gtk-3.0
      - gir1.2-appindicator3-0.1
      - gir1.2-notify-0.7
      - libnotify4
      - gnome-themes-standard
      - inotify-tools
    override-pull: |
      snapcraftctl pull
      VER=$(cat grive_indicator/version)
      REV=$(git rev-parse --short HEAD)
      snapcraftctl set-version $VER-$REV
    override-build: |
      sed -i 's|Icon=web-google-drive|Icon=${SNAP}/usr/share/icons/hicolor/48x48/apps/web-google-drive.png|g' grive_indicator/data/grive-indicator.desktop
      snapcraftctl build
    prime:
      - bin
      - command-*.wrapper
      - lib
      - usr/bin/python*
      - usr/lib/girepository-1.0
      - usr/lib/python3*
      - usr/lib/*/gio
      - usr/lib/*/girepository-1.0
      - usr/lib/*/libdbusmenu*
      - usr/lib/*/libdee*
      - usr/lib/*/libunity*
      - usr/lib/*/libappindicator*
      - usr/lib/*/libindicator*
      - usr/share/applications/grive-indicator.desktop
      - usr/share/icons/hicolor/*/apps/web-google-drive.png
  grive:
    source: https://github.com/vitalif/grive2.git
    plugin: cmake
    build-packages:
      - cmake
      - build-essential
      - libgcrypt11-dev
      - libyajl-dev
      - libboost-all-dev
      - libcurl4-openssl-dev
      - libexpat1-dev
      - libcppunit-dev
      - binutils-dev
      - pkg-config
      - zlib1g-dev
    stage-packages:
      - binutils
      - libboost-filesystem1.65.1
      - libboost-program-options1.65.1
      - libboost-regex1.65.1
      - libboost-system1.65.1
      - libcurl4
      - libgcc1
      - libgcrypt20
      - libstdc++6
      - libyajl2
