name: grive-indicator
version: 'master'
summary: Simple indicator for Grive sync tool
description: |
  This is my-snap's description. You have a paragraph or two to tell the
  most important story about your snap. Keep it under 100 words though,
  we live in tweetspace and your description wants to look good in the snap
  store.

grade: stable
confinement: strict
base: core18

apps:
  grive-indicator:
    command: desktop-launch grive-indicator
    desktop: usr/share/applications/grive-indicator.desktop
    plugs:
      - home
      - network
      - desktop
      - gsettings
      - wayland
      - x11
      - gnome-3-28-1804
      - unity7
      - network-control
    environment:
      XDG_DATA_DIRS: $SNAP/share:$XDG_DATA_DIRS
      GSETTINGS_SCHEMA_DIR: $SNAP/share/glib-2.0/schemas
  grive:
    command: desktop-launch grive
    plugs:
      - home
      - network
      - desktop

plugs:
  gnome-3-28-1804:
    interface: content
    target: gnome-platform
    default-provider: gnome-3-28-1804:gnome-3-28-1804
    content: gnome-3-28-1804
  gtk-3-themes:
    interface: content
    target: $SNAP/data-dir/themes
    default-provider: gtk-common-themes:gtk-3-themes
  icon-themes:
    interface: content
    target: $SNAP/data-dir/icons
    default-provider: gtk-common-themes:icon-themes


slots:
  grive-indicator-dbus:
    interface: dbus
    name: org.app.grive_indicator
    bus: session

parts:
  desktop-gnome-platform:
  
  grive-indicator:
    source: .
    plugin: python
    python-version: python3
    stage-packages:
      - python3-gi
      - python3-dbus
      - python3-requests
      - python3-toml
      - python3-xdg
      - gir1.2-gtk-3.0
      - gir1.2-appindicator3-0.1
      - gir1.2-notify-0.7
      - libnotify4
      - gnome-themes-standard
    override-build: |
     sed -i 's|Icon=web-google-drive|Icon=${SNAP}/usr/share/icons/hicolor/512x512/apps/web-google-drive.png|g' grive_indicator/data/grive-indicator.desktop
     snapcraftctl build
  grive:
    source: https://github.com/vitalif/grive2.git
    plugin: cmake
    build-packages:
      - cmake
      - build-essential
      - libgcrypt11-dev
      - libyajl-dev
      - libboost-all-dev
      - libcurl4-openssl-dev
      - libexpat1-dev
      - libcppunit-dev
      - binutils-dev
      - pkg-config
      - zlib1g-dev
    stage-packages:
      - binutils
      - libboost-filesystem1.65.1
      - libboost-program-options1.65.1
      - libboost-regex1.65.1
      - libboost-system1.65.1
      - libc6
      - libcurl4
      - libgcc1
      - libgcrypt20
      - libstdc++6
      - libyajl2