name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - name: Install dependencies:
      run: |
        pip3 install pipenv
    - name: Run the tests
      uses: actions/checkout@v1
      run: |
        pipenv install --dev
        pipenv run pytest
